#define LED_ONLINE_PIN 3
#define BUZZER_PIN 4
#define SERVO_BACK_PIN 5
#define SERVO_STEERING_PIN 6
#define MOTOR_B_PIN 7
#define MOTOR_A_PIN 8
#define NF_CE_PIN 9
#define NF_CNS_PIN 10
#define NF_MOSI_PIN 11
#define NF_MISO_PIN 12
#define NF_SCK_PIN 13
#define LED_BACK_PIN 18
#define LED_BREAK_PIN 19
#define LED_HIGH_PIN 20
#define LED_LOW_PIN 21